<?php

namespace App\Services\Import;

/**
 * The target field catalog for a CREDENTIAL batch (L8 — legacy diplomas/certificates).
 * Mirrors ImportCourseResultFields's shape — one source of truth for what the mapping
 * screen offers, what validate() requires, and what the committer reads. See
 * docs/legacy-data-import-plan.md §22.1.
 *
 * `credential_type` maps onto the existing `App\Enums\CredentialType` values
 * (TRANSCRIPT, PROGRAM_CERTIFICATE, STANDALONE_CERTIFICATE, OFFERING_COMPLETION) —
 * a registrar tells the importer which of SPIMS's own categories a Populi diploma,
 * transcript, or certificate corresponds to, rather than the importer inventing a new
 * type. `serial` is the source's own certificate/diploma number, kept verbatim — it is
 * never generated by `CredentialService::nextSerial()`, which stays reserved for
 * SPIMS's own issuance.
 */
class ImportCredentialFields
{
    /**
     * @return array<string, string>
     */
    public static function catalog(): array
    {
        return [
            'legacy_id' => 'Legacy student id (must already be linked from a STUDENT batch)',
            'credential_type' => 'Credential type (TRANSCRIPT, PROGRAM_CERTIFICATE, STANDALONE_CERTIFICATE, or OFFERING_COMPLETION)',
            'serial' => "Source's own certificate/diploma number (kept verbatim; never reissued under a SPIMS serial)",
            'issued_at' => 'Original issue date',
            'program_code' => 'Program code (matched against the live catalog only)',
            'language' => 'Language (ar, en, or fr; defaults to en)',
            'signatory_name' => 'Signatory name as it appeared on the original document (optional)',
            'signatory_title' => 'Signatory title as it appeared on the original document (optional)',
        ];
    }

    /**
     * @return array<int, string>
     */
    public static function alwaysRequired(): array
    {
        return ['legacy_id', 'credential_type', 'serial', 'issued_at'];
    }

    /**
     * CREDENTIAL has no population split — the signature is kept identical to the
     * other field-catalog classes so the controller's dispatch can call any of them
     * the same way.
     *
     * @return array<int, string>
     */
    public static function requiredFor(mixed $population = null): array
    {
        return self::alwaysRequired();
    }
}
